name: BudgetLeagueTracker
options:
  bundleIdPrefix: com.budgetleague
  deploymentTarget:
    iOS: "18.0"
  xcodeVersion: "16.0"
settings:
  base:
    SWIFT_VERSION: "6.0"
    SWIFT_STRICT_CONCURRENCY: complete
packages:
  ViewInspector:
    url: https://github.com/nalexn/ViewInspector
    from: 0.10.0
  SnapshotTesting:
    url: https://github.com/pointfreeco/swift-snapshot-testing
    from: 1.15.0
targets:
  BudgetLeagueTracker:
    type: application
    platform: iOS
    sources:
      - path: BudgetLeagueTracker
        type: group
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.budgetleague.BudgetLeagueTracker
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: Budget League Tracker
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
  BudgetLeagueTrackerTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: BudgetLeagueTrackerTests
        type: group
    dependencies:
      - target: BudgetLeagueTracker
      - package: ViewInspector
      - package: SnapshotTesting
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.budgetleague.BudgetLeagueTrackerTests
        GENERATE_INFOPLIST_FILE: YES
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/BudgetLeagueTracker.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/BudgetLeagueTracker"
        BUNDLE_LOADER: "$(TEST_HOST)"
  BudgetLeagueTrackerUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: BudgetLeagueTrackerUITests
        type: group
    dependencies:
      - target: BudgetLeagueTracker
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.budgetleague.BudgetLeagueTrackerUITests
        GENERATE_INFOPLIST_FILE: YES
        TEST_TARGET_NAME: BudgetLeagueTracker
